//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_MessageReceiver
    {
        public int Id { get; set; }
        public System.Guid MessageId { get; set; }
        public System.Guid ToUser { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> FirstReadTime { get; set; }
        public Nullable<System.DateTime> LastReadTime { get; set; }
    }
}
